//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyOneProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnologyOneProject.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology One.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILLION.
        /// </summary>
        public static string Billion {
            get {
                return ResourceManager.GetString("Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create String.
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENT.
        /// </summary>
        public static string Cent {
            get {
                return ResourceManager.GetString("Cent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTS.
        /// </summary>
        public static string Cents {
            get {
                return ResourceManager.GetString("Cents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved: Technology One.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOLLAR.
        /// </summary>
        public static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOLLARS.
        /// </summary>
        public static string Dollars {
            get {
                return ResourceManager.GetString("Dollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIGHT.
        /// </summary>
        public static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIGHTEEN.
        /// </summary>
        public static string Eighteen {
            get {
                return ResourceManager.GetString("Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIGHTY.
        /// </summary>
        public static string Eigthy {
            get {
                return ResourceManager.GetString("Eigthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELEVEN.
        /// </summary>
        public static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNABLE TO CATER FOR VALUE BIGGER THAN: QUADRILLION..
        /// </summary>
        public static string ErrorGettingNumber {
            get {
                return ResourceManager.GetString("ErrorGettingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred:.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFTEEN.
        /// </summary>
        public static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFTY.
        /// </summary>
        public static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIVE.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOUR.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOURTEEN.
        /// </summary>
        public static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOURTY.
        /// </summary>
        public static string Fourty {
            get {
                return ResourceManager.GetString("Fourty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNDRED.
        /// </summary>
        public static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILLION.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINE.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINETEEN.
        /// </summary>
        public static string Nineteen {
            get {
                return ResourceManager.GetString("Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINETY.
        /// </summary>
        public static string Ninety {
            get {
                return ResourceManager.GetString("Ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUADRILLION.
        /// </summary>
        public static string Quadrillion {
            get {
                return ResourceManager.GetString("Quadrillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEVEN.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEVENTEEN.
        /// </summary>
        public static string Seventeen {
            get {
                return ResourceManager.GetString("Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEVENTY.
        /// </summary>
        public static string Seventy {
            get {
                return ResourceManager.GetString("Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIX.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIXTEEN.
        /// </summary>
        public static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIXTY.
        /// </summary>
        public static string Sixty {
            get {
                return ResourceManager.GetString("Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEN.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIRTEEN.
        /// </summary>
        public static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIRTY.
        /// </summary>
        public static string Thirty {
            get {
                return ResourceManager.GetString("Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THOUSAND.
        /// </summary>
        public static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREE.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRILLION.
        /// </summary>
        public static string Trillion {
            get {
                return ResourceManager.GetString("Trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWELVE.
        /// </summary>
        public static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWENTY.
        /// </summary>
        public static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWO.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Calculate. You have too much money.
        /// </summary>
        public static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
